; *******************************************************
; * Utility Routines for CP/M Applications              *
; * Version: V1.0                                       *
; * Merlin Skinner-Oakes, 22/3/2021                     *
; *******************************************************
;
; Support routines for use with CP/M applications. Character I/O is performed
; using BIOS routines (rather than the BDOS) as this avoids unwanted echoing of
; input, for example. BDOS features such as tab expansion are not that useful
; as they are easily confused by ANSI control codes, for example.
;
; Routines preserve all registers not required as operands or return
; values except AF unless otherwise stated below.
;
;
                title Utilites
;
CPMU            equ 1                   ; Flag module for includes
;DEBUG           equ 1                   ; Enable debugging messages
;
;
;
; ************
; * Includes *
; ************
;
;
                include "macros.i"
                include "z80.i"
                include "terminal.i"    ; Terminal constants
                include "cpm.i"
                include "cpm_utility.i"
;
;
;
; *************
; * Externals *
; *************
;
;
; Variables
; None.
;
; Functions.
; CP/M specific.
                public init     ; Common initialisation code
                public conmod   ; Set console mode (BDOS or BIOS)
                public cbdos    ; Call BDOS with some registers saved
                public cbios    ; Call BIOS with some registers saved
                public panic    ; Fatal application error
                public zrcdet   ; Detect ZARC
                public z80det   ; Detect Z80 (instead of 8080 / 8085)
                public clopts   ; Read command line options
;
; Derived from the monitor's utility.z80.
                public conwch   ; Write character to console
                public conrch   ; Read character from the console
                public const    ; Fetch console input status
                public cwnwln   ; Write new line characters to console
                public conwms   ; Print "$" terminated string to the console
                public conwmn   ; Print message <n> in a list
                public skpspc   ; Step hl past spaces
                public toupca   ; Convert character in A to upper case
                public toloca   ; Convert character in A to lower case
                public cwvich   ; Print only visible 7-bit characters
                public cwpspc   ; Print a space
                public mtwdli   ; Match word in a string against list of options
                public cwphnb   ; Print least-significant nibble in A in hexadecimal
                public cwphby   ; Print A in hexadecimal
                public cwphwd   ; Print HL in hexadecimal
                public cwpdwd   ; Print HL in decimal. Leading zeros are suppressed
                public cwpdby   ; Print A in decimal. Leading zeros are suppressed
                public cwpdwd   ; Print HL in decimal. Leading zeros are suppressed
                public cwpdlo   ; Print DEHL in decimal. Leading zeros are suppressed
                public rdhxwd   ; Read a 16-bit hexadecimal number from a string
                public rdduwd   ; Read a 16-bit unsigned decimal number from a string
                public rddulo   ; Read a 32-bit unsigned decimal number from a string
;
; Variables
                public cpmver   ; CP/M version (packed BCD)
;
;
;
; ********
; * Code *
; ********
;
;
                cseg                    ; Code segment
;
;
; Common initialisation code. The initial code does not assume a Z80 so we can
; exit cleanly if this is run on an 8080, for example.
init            push bc
                push de

; Determine CPU type.
                call z80det             ; Detect Z80 (instead of 8080 / 8085)
                jp nc, it_on_z80        ; Jump if we have a Z80
;
; 8080 / 8085 detected. Print message and exit. We can't use conwms as this
; assumes a Z80.
                ld de, no_z80_msg       ; "Z80 CPU required"
; Display message in DE and return to CP/M.
it_msg_exit     ld c, BDOS_PRINT_STRING ; Print String
                call BDOS
                rst 0                   ; Warm boot
;
; Set console output via BDOS, at least initially.
it_on_z80       ld a, CONMOD_BDOS
                call conmod
;
; Find out which version of CP/M we are running on.
                ld c, BDOS_VERSION      ; Return BDOS Version Number
                call cbdos              ; Call BDOS with some registers saved
; Returns B=H=system type, A=L=version number.
                ld a, h                 ; MSN=CPU type, LSN=CP/M type
                and a
                jr nz, os_error
; Match version against those supported. It is likely that others are OK too,
; but I can't test all combinations.
                ld a, l                 ; OS Version number
                cp 0x20
                jr z, it_cpm_ok
                cp 0x21
                jr z, it_cpm_ok
                cp 0x22
                jr z, it_cpm_ok
                cp 0x30
                jr z, it_cpm_ok
                cp 0x31
                jr z, it_cpm_ok
;
; Go here if we don't like or can't recognise the operating system we are
; running on.
os_error        ld de, unsupp_os_msg
                jr it_msg_exit          ; Display message and exit
;
; We are running on a system we know about.
it_cpm_ok       ld (cpmver), a
;
                pop de
                pop bc
                ret
;
;
; Set console mode (BDOS or BIOS). Call with:
; A - CONMOD_BDOS or CONMOD_BIOS as required.
conmod          push de
                push hl
;
                ld hl, con_bdos_funcs   ; Point to list of BDOS routines
                cp CONMOD_BDOS
                jr z, cm_set
                ld hl, con_bios_funcs   ; Point to list of BIOS routines
                cp CONMOD_BIOS
                jr z, cm_set
                call panic              ; Panic if value is bad
;
cm_set          ld de, conwch_vec       ; Point to first vector
                ld bc, 4 * 2            ; Four vectors to copy
                ldir
;
                pop hl
                pop de
                ret
;
;
; Call BDOS with IX and IY registers saved.
cbdos           push ix
                push iy
;
; Write BDOS call parameters to console for debugging. E.g.:
; [BDOS 12-F_OPEN, 1DAB] 
                ifdef DEBUG
                    push bc
                    push de
                    push hl
                    call cwnwln         ; Write new line to console
                    ld hl, bdos_msg     ; "[BDOS "
                    call conwms         ; Print $-terminated string to console
                    ld a, c
                    call cwpdby         ; Print A in decimal
                    ld a, "-"
                    call conwch         ; Write character to console
                    ld a, c
                    ld c, "\"           ; Separator
                    ld hl, bdos_func_list
                    call conwmn         ; Print message <n> in a list
                    ld a, ","
                    call conwch         ; Write character to console
                    ld a, " "
                    call conwch         ; Write character to console
                    ex de, hl
                    call cwphwd         ; Print HL in hexadecimal
                    ld a, "]"
                    call conwch         ; Write character to console
                    call cwnwln         ; Write new line to console
                    pop hl
                    pop de
                    pop bc
                endif
;
                call BDOS
                pop iy
                pop ix
                ret
;
;
; Call BIOS with some registers saved.
; Call with:
; BC - operand (depends on BIOS function called)
; DE - operand (depends on BIOS function called)
; HL - offset for the routine (e.g. BIOS_CONIN)
cbios           push ix
                push iy
                call cbios_raw
                pop iy
                pop ix
                ret
;
;
; Call BIOS, allowing for its unknown base address.
; Call with:
; BC - operand (depends on BIOS function called)
; DE - operand (depends on BIOS function called)
; HL - offset for the routine (e.g. BIOS_CONIN)
; BIOS_WBOOT is not supported as it is easily replicated by a jump to 0.
cbios_raw       push de
; 
; From the CP/M 3 Programmers Guide:
;   Under CP/M 3, direct BIOS calls via the BIOS jump vector are only supported
;   for the BIOS Console I/O and List functions. You must use Function 50 to
;   call any other BIOS functions. In addition, Function 50 intercepts BIOS
;   Function 27 (Select Memory) calls and returns with register A set to zero.
; As BDOS_S_BIOS is likely to be very slow, first ascertain whether we can use
; the CP/M 2.x method.
                ld a, h
                and a
                call nz, panic          ; BIOS jump block is < 256 bytes long
                ld a, l
                and a
                call z, panic           ; BIOS_WBOOT not supported
                cp BIOS_CONOST
                jr z, cbios_direct      ; Use direct method
                cp BIOS_LISTST
                jr z, cbios_direct      ; Use direct method
                cp BIOS_PUNCH           ; First non-direct function
                jr c, cbios_direct      ; Use direct method
                cp BIOS_ID              ; First ZARC extension
                jr nc, cbios_direct     ; Use direct method
;
; Under CP/M 3.x we must use BDOS_S_BIOS but for CP/M 2.x we must use the direct
; method as BDOS_S_BIOS is not supported.
                ld a, (cpmver)          ; CP/M version (packed BCD)
                and 0xf0                ; Isolate major version
                cp 0x30
                jr c, cbios_direct      ; Jump if running on earlier than 3.0
;
; Use BDOS_S_BIOS.
                ld ix, cbios_params
                ld (ix + SBM_B), b
                ld (ix + SBM_C), c
                pop de
                ld (ix + SBM_D), d
                ld (ix + SBM_E), e
; Find function number (L / 3) + 1. This is slow, but not required that often.
                ld b, 3
                ld c, 1                 ; Function number
                ld a, l
cbios_div_lp    inc c
                sub b
                call c, panic
                jr nz, cbios_div_lp
                ld (ix + SBM_FUNC), c
                push ix
                pop de
                ld c, BDOS_S_BIOS       ; Use the BIOS
                jp BDOS                 ; Call BDOS and return to caller
; Returned values are those directly from the BIOS.
;
; Jump directly to BIOS for CP/M 2.x and earlier.
cbios_direct    ex de, hl
                ld hl, (1)              ; Find WBOOT (warm boot) address
                add hl, de              ; Add offset
; BC - operand (depends on BIOS function called)
; HL - routine entry point
                pop de
                jp (hl)                 ; Jump to BIOS then return to caller
;
;
; Unrecoverable application error! Halt the application to prevent further
; damage. Call this routine in case of a serious error.
; Note: call is preferred (rather than jump) as it preserves the PC.
panic           ld hl, panic_1_msg      ; "*** Software panic at PC="
                call conwms             ; Print $-terminated string to console
                pop hl                  ; Fetch PC
                call cwphwd             ; Print HL in hexadecimal
                ld hl, panic_2_msg      ; " ***"
                call conwms             ; Print $-terminated string to console
                jp 0                    ; Warm boot
;
;
; Determine whether or not we are running on a ZARC system. Returns with carry
; set if ZARC BIOS not found.
zrcdet          push de
                push hl
                ld de, BIOS_ID          ; ID offset into BIOS jump table
                ld hl, (1)              ; Find WBOOT (warm boot) address
                add hl, de              ; Add offset
                ld a, (hl)
                cp "Z"
                jp nz, zd_not_zarc
                inc hl
                ld a, (hl)
                cp "R"
                jp nz, zd_not_zarc
                inc hl
                ld a, (hl)
                cp "C"
                jp nz, zd_not_zarc
                and a               ; Flag success
;
zd_exit         pop hl
                pop de
                ret
;
; ZARC BIOS not found.
zd_not_zarc     scf
                jr zd_exit
;
;
; Determine whether we are running on a Z80 system. Returns with carry set if
; the processor appears to be something else (8080 or 8085). Take care when
; modifying this code, as it has to support all CPU types.
z80det          push bc
;
                xor a
                and a
; From https://ee.sharif.edu/~sakhtar3/articles/8080-8085/8085%20Instruction%20Set.pdf
; ANA r ... The CY flag is cleared and the AC is set (8085). The CY is cleared
; and the AC is set to the OR'ing of bits 3 of the operands (8080).
; The Z80 calls AC "half-carry" (H) and behaves like an 8085 in this regard.
                push af
                pop bc
                ld a, c                 ; Flags
                and 0x10                ; Isolate AC / half-carry
                jp z, z8d_not_z80       ; Jump if 8080
; 8085 or Z80. Using the method described at:
; https://heavydeck.net/post/i8085-rl35902-z80-run-time-detection/
; ... exploit the difference on byte 0x20 which on the i8085 translates to RIM
; (Read Interrupt Mask) opcode and on the z80 ... is a two-byte relative jump
; JR NZ n.
                xor a
                inc a                   ; Reset Z flag
; The following (0x20, 0x04) is interpreted as RIM, INR B on an 8085.
                jr nz, z8d_z80
                nop                     ; 1
; This must be an 8085.
                jp z8d_not_z80          ; 3
;
; There must be four bytes between the jr nz / RIM instruction and this point
; for this to work.
z8d_z80         and a                   ; Flag success
z8d_exit        pop bc
                ret
;
; Z80 not found.
z8d_not_z80     scf
                jp z8d_exit             ; No "jr" on 8080 / 8085!
;
;
; Write character to console. This "looks like" the monitor's routine of the
; same name, thereby easing the use of monitor routines copied here. 
; Call with:
; A - character to write.
conwch          push bc
                push de
                push hl
;
                ld hl, cw_ret           ; Return to this address
                push hl
                ld hl, (conwch_vec)
                jp (hl)
;
cw_ret          pop hl
                pop de
                pop bc
                ret
;
; BDOS version.
conwch_bdos     ld e, a
                ld c, BDOS_CON_OUT      ; Console output
                jp cbdos
;
; BIOS version.
conwch_bios     ld c, a
                ld hl, BIOS_CONOUT      ; Console output
                jp cbios              ; Call BIOS
;
;
; Read character from the console. This "looks like" the monitor's routine of
; the same name, thereby easing the use of monitor routines copied here. There
; are some differences between how the BIOS and BDOS routines behave.
; BDOS: echoes input to the display. Processes XON / XOFF, ^P etc.
; BIOS: raw input with no echo.
; Returns with:
; A - character.
conrch          push bc
                push de
                push hl
;
                ld hl, cr_ret           ; Return to this address
                push hl
                ld hl, (conrch_vec)
                jp (hl)
;
cr_ret          pop hl
                pop de
                pop bc
                ret
;
; BDOS version. Note that this could be modified to use BDOS function 6 (RAWIO),
; which would avoid the echo. However, it would also disable ^S and ^P, for
; example.
conrch_bdos     ld c, BDOS_CON_IN       ; Console input
                jp cbdos
;
; BIOS version.
conrch_bios     ld hl, BIOS_CONIN       ; Console input
                jp cbios                ; Call BIOS
;
;
; Write new line characters to console.
cwnwln          ld a, ascii_cr
                call conwch
                ld a, ascii_lf
                jp conwch
;
;
; Fetch the console input status. Returns with:
; A - zero if no character is ready, non-zero if one is.
const           push bc
                push de
                push hl
;
                ld hl, cs_ret           ; Return to this address
                push hl
                ld hl, (const_vec)
                jp (hl)
;
cs_ret          pop hl
                pop de
                pop bc
                ret

; BDOS version.
const_bdos      ld c, BDOS_GET_CON_STAT     ; Console status
                jp cbdos
;
const_bios      ld hl, BIOS_CONST       ; Console status
                jp cbios
;
;
; Print "$" terminated string to the console. Note, this is different to the
; monitor version in that it uses the "$" CP/M terminator instead of a null. It
; also does not return with the address of the terminator in HL.
; Call with:
; HL - pointer to start of message
conwms          push bc
                push de
;
                ex de, hl               ; Move pointer to HL
                ld hl, cwm_ret          ; Return to this address
                push hl
                ld hl, (conwms_vec)
                jp (hl)
;
cwm_ret         pop de
                pop bc
                ret
;
; BDOS version.
conwms_bdos     ld c, BDOS_PRINT_STRING ; Print String
                jp cbdos
;
; BIOS version.
conwms_bios     ex de, hl
cwsb_loop       ld a, (hl)
                cp "$"
                ret z
                call conwch             ; Write character to console
                inc hl
                jr cwsb_loop
;
;
; Step HL past any spaces.
; Returns with:
; HL - points to the first non-space character
skpspc          ld a, ' '
sks_loop        cp (hl)
                ret nz                  ; Return if non-space found
                inc hl
                jr sks_loop
;
;
; Convert character in A to upper case.
toupca          cp 'a'
                ret c                   ; Nothing to do if < 'a'
                cp 'z' + 1
                ret nc                  ; Nothing to do if > 'z'
                sub 'a' - 'A'
                ret
;
;
; Convert character in A to lower case.
toloca          cp 'A'
                ret c                   ; Nothing to do if < 'A'
                cp 'Z' + 1
                ret nc                  ; Nothing to do if > 'Z'
                add 'a' - 'A'
                ret
;
;
; Print a space.
cwpspc          ld a, ' '
                jp conwch
;
;
; Print only visible 7-bit characters. Non-visible ones are substituted by the
; character in C. If C is 0xff, non-visible characters are displayed in
; hexadecimal. Call with:
; A - character to display
; C - substution character. If C is zero, non-visible characters are displayed
; in hexadecimal.
; Note that the hexadecimal feature is not included in the monitor version of
; this function. 
cwvich          push bc
                ld b, a                 ; Save character
                cp ' '
                jr c, prv_do_subs       ; < ' ' is a control character
                cp ascii_del
                jr nc, prv_do_subs      ; >= DEL isn't visible either
; Character is printable.
prv_dis_exit    call conwch             ; Print visible character
prv_exit        pop bc
                ret
;
; Use substitution character
prv_do_subs     ld a, c
                and a
                jr nz, prv_dis_exit
;
; Display in hexadecimal.
                ld a, "{"
                call conwch             ; Write character to console
                ld a, b
                call cwphby             ; Print A in hexadecimal
                ld a, "}"
                jr prv_dis_exit         ; Print and exit
;
;
; Print least-significant nibble in A in hexadecimal.
cwphnb          and 0x0f
                add '0'
                cp '9' + 1
                jr c, pn_numeric        ; Jump if <= '9'
                add ('A' - '9') - 1     ; Convert to alpha
pn_numeric      jp conwch
;
;
; Print A in hexadecimal.
cwphby          push af
                rrca
                rrca
                rrca
                rrca
                call cwphnb             ; Print MSN
                pop af
                jp cwphnb               ; Print LSN
;
;
; Print HL in hexadecimal. Leading zeros are suppressed.
cwphwd          ld a,h
                call cwphby             ; Print MSB
                ld a,l
                jp cwphby               ; Print LSB
;
;
; Print A as a decimal unsigned number. Leading zeros are suppressed.
cwpdby          push bc
                push de
                push hl
                ld e, 0                 ; Leading zeros flag
                ld h, 0                 ; Move A to HL
                ld l, a
                jr pdw_byte             ; Use word code, skipping MS digits
;
;
; Print HL as a decimal unsigned number. Leading zeros are suppressed.
; Derived from code at http://map.grauw.nl/sources/external/z80bits.html
; HL is saved because this allows common exit code with cwpdby.
cwpdwd          push bc
                push de
                push hl
                ld e, 0                 ; Leading zeros flag
; Entry point from cwpdlo (32-bit version).
                ld bc, -10000           ; 10^4
                call pdw_digit
pdl_entry       ld bc, -1000            ; 10^3
                call pdw_digit
; cwpdby enters here to display a single byte.
pdw_byte        ld bc, -100             ; 10^2
                call pdw_digit
                ld c, -10               ; 10^1
                call pdw_digit
                ld e, 0xff              ; Always print the units digit
                ld c, b
                call pdw_digit
                pop hl
                pop de
                pop bc
                ret
;
pdw_digit       ld a, '0' - 1
pdw_digloop     inc a
                add hl, bc
                jr c, pdw_digloop
                sbc hl, bc
; A - ASCII digit
                cp '0'
                jr nz, pdw_prdig        ; Non-zero digit, so print it
                inc e
                jr z, pdw_prdig         ; Print anyway if e was 0xff
                dec e                   ; Restore flag
                ret
pdw_prdig       ld e, 0xff              ; Flag non-zero found
                call conwch             ; Write character to console
                ret
;
;
; Print DEHL as a decimal unsigned number. Leading zeros are suppressed.
cwpdlo          push bc
                ld b, h
                ld c, l
; DEBC - value to display. Store this.
                ld hl, pdl_reg
                ld (hl), c
                inc hl
                ld (hl), b
                inc hl
                ld (hl), e
                inc hl
                ld (hl), d
; Reset leading zeros flag
                ld a, 0
                ld (pdl_lz_flag), a
; Digits
                ld de, 0xca00           ; 10^9
                ld bc, 0x3b9a
                call pdl_digit
                ld de, 0xe100           ; 10^8
                ld bc, 0x05f5
                call pdl_digit
                ld de, 0x9680           ; 10^7
                ld bc, 0x0098
                call pdl_digit
                ld de, 0x4240           ; 10^6
                ld bc, 0x000f
                call pdl_digit
                ld de, 0x86a0           ; 10^5
                ld bc, 0x0001
                call pdl_digit
                ld de, 0x2710           ; 10^4
                ld bc, 0x0000
                call pdl_digit
; Use 16-bit version to print the remainder of the digits.
                push de
                push hl
; Fetch value.
                ld hl, pdl_reg
                ld e, (hl)
                inc hl
                ld d, (hl)
                ex de, hl
                ld a, (pdl_lz_flag)
                ld e, a                 ; Set leading zeros flag
; E - leading zeros flag
; HL - value to print
                jp pdl_entry
;
; BCDE - significance of digit.
pdl_digit       ld hl, pdl_ascii
                ld (hl), '0' - 1
pdl_digloop     inc (hl)                ; Update ASCII digit
; Trial subtraction.
                push hl                 ; Save pointer to pdl_ascii
                ld hl, pdl_reg
                ld a, (hl)
                sub e
                ld (hl), a
                inc hl
                ld a, (hl)
                sbc d
                ld (hl), a
                inc hl
                ld a, (hl)
                sbc c
                ld (hl), a
                inc hl
                ld a, (hl)
                sbc b
                ld (hl), a
                pop hl                  ; Restore pointer to pdl_ascii
                jr nc, pdl_digloop      ; Keep subtracting until carry
; Reverse the last subtraction to restore the value before carry.
                ld hl, pdl_reg
                ld a, (hl)
                add e
                ld (hl), a
                inc hl
                ld a, (hl)
                adc d
                ld (hl), a
                inc hl
                ld a, (hl)
                adc c
                ld (hl), a
                inc hl
                ld a, (hl)
                adc b
                ld (hl), a
;
                ld hl, pdl_lz_flag      ; Point to leading zeros flag
                ld a, (pdl_ascii)       ; Fetch ASCII digit
                ld c, a
                cp '0'
                jr nz, pdl_prdig        ; Non-zero digit, so print it
                ld a, (hl)
                and a
                jr nz, pdl_prdig        ; Print anyway if flag was set
; Skip leading zeros.
                ret
;
pdl_prdig       ld (hl), 0xff           ; Flag non-zero found
                ld a, c
                call conwch
                ret
;
;
; Print message <n> in a null terminated list. Nothing is printed if the
; terminator is encountered before message <n> is found.
; Call with:
; A - number of message to print (first is zero)
; C - message separator
; HL - pointer to start of message
; Returns with:
; HL - points to the separator at the end of the message printed, or the
; terminator (zero).
; Carry flag is set if the message was not found (terminator encountered).
conwmn          push bc
                ld b, a                 ; Message number
pmn_msg_lp      ld a, b
                and a
                jr z, pmn_found         ; Jump if this is the one
; Skip to next message.
pmn_sk_lp       ld a, (hl)
                and a
                jr z, pmn_error         ; Error if terminator
                inc hl
                cp c
                jr nz, pmn_sk_lp        ; Keep going if not separator or terminator
; Separator found
                dec b
                jr pmn_msg_lp
; HL now points to the requied message. Print it until the separator or
; terminator is encountered.
pmn_found       ld a, (hl)
                and a
                jr z, pmn_done          ; Exit if terminator found
                cp c
                jr z, pmn_done          ; Exit if separator found
                call conwch             ; Write character to console
                inc hl                  ; Increment character pointer
                jr pmn_found            ; Transmit next character
; Successful completion.
pmn_done        pop bc
                and a
                ret                     ; Return with carry reset (no error)
; Terminator encountered before the message was found
pmn_error       pop bc                  ; Restore registers
                scf
                ret                     ; Return with carry set (error)
;
;
; Match word in a string against list of options. This is intended for matching
; a command string against a list of available commands, but it may have other
; uses. Strings to match may optionally be abbreviated by a ".", in which case
; the first option that matches up to this is returned. This is similar to the
; BBC Microcomputer method of abbreviating commands.
; Call with:
; A - Options (MTWDLI_xxx, e.g. MTWDLI_ABBREV). See cpm_utility.i
; HL - points to start of string. Matching stops at a space or end of string.
; DE - points to null terminated command list. Options are separated by spaces.
; Returns with:
; A - index number of word in list that matched, or zero if no match.
; HL - points to space or terminator in string.
mtwdli          push bc                 ; Preserve BC
                push hl                 ; Save start of word in string
                ld c, a                 ; Save options
                ld b, 1                 ; Word count
mw_char_loop    res MTWDLI_TERM_BIT, c  ; Flag no terminator found (yet)
; End of word or end of string?
; C - bit 0 is abbreviation enable, bit 1 is terminator found.
                ld a, (hl)              ; Fetch character from string
                cp ' '
                jr z, mw_sword_end
                and a
                jr z, mw_sword_end
; Check for abbreviation character if enabled.
                bit MTWDLI_ABBREV_BIT, c    ; Abbreviations enabled?
                jr z, mw_str_tm_dn
                cp '.'
                jr z, mw_dot            ; Stop matching if "." found.
                jr mw_str_tm_dn
; Flag end of word or end of string found
mw_sword_end    set MTWDLI_TERM_BIT, c  ; Flag this for later
; Repeat test for word list.
mw_str_tm_dn    ld a, (de)              ; Fetch character from list
                cp ' '
                jr z, mw_end_lwd        ; End of word in list
                and a
                jr z, mw_end_lwd        ; End of word in list
                bit MTWDLI_ICASE_BIT, c ; Force lower case?
                call nz, toloca         ; Optionally convert to lower case
; There is at least one more character to match in the string and the current word
; in the list.
                push bc                 ; Save counter
                ld b, a
                ld a, (hl)
                bit MTWDLI_ICASE_BIT, c ; Force lower case?
                call nz, toloca         ; Optionally convert to lower case
                cp b
                pop bc
                jr nz, mw_char_mis
; Characters matched!
                inc hl
                inc de
                jr mw_char_loop
; Mismatch. Try the next word in the list, if there is one.
mw_char_mis     pop hl                  ; Reset string pointer
                push hl
                inc b                   ; Keep track of word count
; Skip forward until the next item in the list, or the end of the list
mw_next_lwd     inc de
                ld a, (de)
                and a
                jr z, mw_no_match       ; Exit if end of word list encountered
                cp ' '
                jr nz, mw_next_lwd
                inc de                  ; Point to first character of next word
                jr mw_char_loop         ; Try this one
;
; End of word found in list.
mw_end_lwd      bit MTWDLI_TERM_BIT, c  ; Terminator found?
                jr nz, mw_end_both
; End of word found in list, but not in the string.
                dec de                  ; Allow for increment later
                jr mw_char_mis          ; Try next word in list
;
; End of the word list reached and no match.
mw_no_match     pop hl                  ; Fix stack
                xor a                   ; Flag no match
                pop bc                  ; Restore BC
                ret
;
; End of words in string and list found simultanously. We have a match!                
mw_end_both     inc sp                  ; Fix stack
                inc sp
                ld a, b                 ; Fetch word index number
                pop bc                  ; Restore BC
                ret
;
; "." found in string, so accept the current word as the match. We need to skip the
; remainder of the string.
mw_dot          inc hl                  ; Step past dot
                jr mw_end_both
;
;
; Read a 16-bit hexadecimal number from a string. Case is ignored for alphabetic
; characters.
; Call with:
; HL - points to the first character of the number.
; Returns with:
; HL - points to first character after number.
; DE - required number
; C flag - set on error (too many or zero valid digits)
rdhxwd          push bc
                ld de, 0                ; Initial result
                ld c, 0                 ; Count characters read
ghn_char_lp     ld a, (hl)
                call toupca             ; Convert to upper case.
                cp 'A'
                jr c, ghn_not_alpha
                cp 'F' + 1
                jr nc, ghn_not_alpha
; Character is alphabetic.
                sub 'A' - 10
                jr ghn_got_dig
; Character is not alphabetic.
ghn_not_alpha   sub '0'
                jr c, ghn_done          ; End of number if < '0'
                cp 10
                jr nc, ghn_done         ; End of number if not a digit
; Value of digit is in LSN of A. Make space for it in the result.
ghn_got_dig     ex de, hl
                add hl, hl              ; Shift left
                jr c, ghn_error_ex      ; No bits should fall off the end
                add hl, hl
                jr c, ghn_error_ex      ; No bits should fall off the end
                add hl, hl
                jr c, ghn_error_ex      ; No bits should fall off the end
                add hl, hl
                jr c, ghn_error_ex      ; No bits should fall off the end
                ex de, hl
; Insert new digit
                or e
                ld e, a
; Count digits and check limit.
                inc hl                  ; Point to next character
                inc c                   ; One more digit
                jr nz, ghn_char_lp      ; Keep going unless over limit
                jr ghn_error
; Too many or zero digits or overflow.
ghn_error_ex    ex de, hl
ghn_error       pop bc
                scf
                ret                     ; Return with carry flag set (error)
; Non-hex character found.
ghn_done        ld a, c
                and a
                jr z, ghn_error         ; Error if no digits read
; Normal completion.
                pop bc
                ret                     ; Return with carry flag reset (OK)
;
;
; Read a 16-bit unsigned decimal number from a string.
; Call with:
; HL - points to the first character of the number.
; Returns with:
; HL - points to first character after number.
; DE - required number
; C flag - set on error (too many or zero valid digits)
rdduwd          push bc
                ld de, 0                ; Initial result
                ld c, 0                 ; Count characters read
gdn_char_lp     ld a, (hl)
                sub '0'
                jr c, gdn_done          ; End of number if < '0'
                cp 10
                jr nc, gdn_done         ; End of number if not a digit
; Value of digit is in LSN of A. Make space for it in the result.
                push bc                 ; Save counter
                ex de, hl
                ld b, h                 ; Save result x 1
                ld c, l
                add hl, hl              ; Find result x 2
                jr c, gdn_error_pop     ; No bits should fall off the end
                add hl, hl              ; Find result x 4
                jr c, gdn_error_pop
                add hl, bc              ; Find result x 5
                jr c, gdn_error_pop                
                add hl, hl              ; Find result x 10
                jr c, gdn_error_pop
; Insert new digit
                ld b, 0
                ld c, a
                add hl, bc              ; Add digit
                jr c, gdn_error_pop
                ex de, hl
                pop bc                  ; Restore counter
; Count digits and check limit.
                inc hl                  ; Point to next character
                inc c                   ; One more digit
                jr nz, gdn_char_lp      ; Keep going unless 256 digits (unlikely)
                jr gdn_error
; Too many or zero digits or overflow.
gdn_error_pop   ex de, hl               ; Move pointer back to HL
                pop bc                  ; Clean up stack
gdn_error       pop bc                  ; Restore original BC
                scf
                ret                     ; Return with carry flag set (error)
; Non-digit character found.
gdn_done        ld a, c
                and a
                jr z, gdn_error         ; Error if no digits read
; Normal completion.
                pop bc
                ret                     ; Return with carry flag reset (OK)
;
;
; Read a 32-bit unsigned decimal number from a string.
; Call with:
; HL - points to the first character of the number.
; Returns with:
; HL - points to first character after number.
; BCDE - required number
; C flag - set on error (too many or zero valid digits)
rddulo          ld bc, 0                ; Initial result
                ld d, b
                ld e, c
                ld a, 0                 ; Count characters read
gldn_char_lp    push af                 ; Save counter
                ld a, (hl)
                sub '0'
                jr c, gldn_done         ; End of number if < '0'
                cp 10
                jr nc, gldn_done        ; End of number if not a digit
; Value of digit is in LSN of A. Make space for it in the result.
                push hl                 ; Save pointer
                push af                 ; Save digit
; Save result x 1 
                ld hl, gldn_x1
                ld (hl), e
                inc hl
                ld (hl), d
                inc hl
                ld (hl), c
                inc hl
                ld (hl), b
; Find result x 2
                sla e
                rl d
                rl c
                rl b
                jr c, gldn_error_pop    ; No bits should fall off the end
; Find result x 4
                sla e
                rl d
                rl c
                rl b
                jr c, gldn_error_pop    ; No bits should fall off the end
; Add "x 1" to obtain result x 5
                ld hl, gldn_x1
                ld a, e
                add (hl)
                ld e, a
                inc hl
                ld a, d
                adc (hl)
                ld d, a
                inc hl
                ld a, c
                adc (hl)
                ld c, a
                inc hl
                ld a, b
                adc (hl)
                ld b, a
                jr c, gldn_error_pop    ; No bits should fall off the end
; Find result x 10
                sla e
                rl d
                rl c
                rl b
                jr c, gldn_error_pop    ; No bits should fall off the end
                pop af                  ; Restore digit
; Insert new digit
                ld l, 0                 ; Cache zero
                add e
                ld e, a
                ld a, l
                adc d
                ld d, a
                ld a, l
                adc c
                ld c, a
                ld a, l
                adc b
                ld b, a
                jr c, gldn_error_pop    ; No bits should fall off the end
; BCDE - required number
                pop hl                  ; Restore pointer
; Count digits and check limit.
                inc hl                  ; Point to next character
                pop af                  ; Restore counter
                inc a                   ; One more digit
                jr nz, gldn_char_lp     ; Keep going unless 256 digits (unlikely)
                jr gldn_error
; Too many or zero digits or overflow.
gldn_error_pop  pop hl                  ; Restore pointer
                pop af                  ; Discard counter
gldn_error      scf
                ret                     ; Return with carry flag set (error)
; Non-digit character found.
gldn_done       pop af                  ; Restore counter
                and a
                jr z, gldn_error        ; Error if no digits read
; Normal completion.
                ret                     ; Return with carry flag reset (OK)
;
;
; Read command line options. Up to 8 option characters are allowed.
; Call with:
; DE - points to a null terminated list of option characters.
; HL - points to the current position in the command line.
; Returns with:
; A - option flags.
; HL - points to first character after options and any trailing spaces.
; C flag - set on error (malformed option string)
; Each bit in A corresponds to one character in the options list. Bit 0 is set
; of the first character is encountered, bit 1 for the second and so on. Options
; may begin with "[", "/" or "$", to match all conventions I have found used
; with CP/M. If no options are included in the command line, A will be set to
; zero (no options set). Option characters may include any printable character
; except space or "]". Lower case is not permitted. Duplicates are ignored.
clopts          push bc
;
                ld c, 0                 ; Set default options
; Check for options. These may begin with "[", "/" or "$", to match all
; conventions I have found used with CP/M.
                call skpspc             ; Skip spaces
; Options
                ld a, (hl)
                ld b, a                 ; Save for later
                and a
                jr z, clo_end_opts      ; Jump if no options 
                cp "["
                jr z, clo_op_loop
                cp "/"
                jr z, clo_op_loop
                cp "$"
                jr z, clo_op_loop
; We have found a character, but it isn't an option introducer. We return with
; HL pointing to this character we didn't recognise.
                and a
                jr clo_exit             ; Exit with no options
;
; Option loop. Attempt to match each option character with the list of options.
; B - option introducer character
; C - option flags (initially zero)
; DE - points to a null terminated list of option characters.
; HL - pointer to command line
clo_op_loop     inc hl
; A terminator or space ends the option string. If the introducer is a "[",
; a closing "]" is required.
                ld a, "["
                cp b
                ld a, (hl)              ; Fetch character from command line
                jr nz, clo_not_brktd    ; Jump if we didn't start with "["
; Options started with a "[" so must finish with a "]".
                and a
                jr z, clo_err
                cp " "
                jr z, clo_err
                cp "]"
                jr nz, clo_do_opt
                inc hl                  ; Step past "]"
                jr clo_end_opts         ; Exit
; Options were started with "/" or "$" so there is no explicit terminator.
clo_not_brktd   and a
                jr z, clo_end_opts
                cp " "
                jr z, clo_end_opts
;
; Process option character.
clo_do_opt      ld a, (hl)              ; Re-fetch character
                push de                 ; Save address of option characters
                ex de, hl
                push bc                 ; Save introducer and flags
                ld c, a
                ld b, 1                 ; Flag bit mask
; B - flag bit mask
; C - option character
; HL - points to a null terminated list of option characters.
; DE - pointer to command line
clo_ch_loop     ld a, (hl)              ; Fetch option character
                and a
                jr z, clo_miss          ; Jump if terminator found
                inc hl
                cp c
                jr z, clo_match
                rlc b                   ; Update mask
                call c, panic           ; Panic if too many options
                jr clo_ch_loop
;
; Match found.
clo_match       ex de, hl
                ld a, b                 ; Mask
                pop bc                  ; Fetch introducer and flags
                or c                    ; Update flags
                ld c, a
                pop de                  ; Restore pointer to start of list
                jr clo_op_loop          ; Process next character
;
; We found the terminator while searching the list of possible options.
clo_miss        pop bc                  ; Fetch introducer and flags 
                pop de                  ; Restore pointer to start of list
;
; Return with error.
clo_err         scf                     ; Flag error
                jr clo_exit
;
; Normal return.
clo_end_opts    and a                   ; Flag OK
clo_exit        ld a, c                 ; Move option flags to A
                pop bc
; Skip any trailing spaces.
                push af
                call skpspc             ; Skip spaces
                pop af
                ret
;
;
;
; *************
; * Constants *
; *************
;
;
panic_1_msg     byte 0x0d, 0x0a, "*** Software panic at PC=", "$"
panic_2_msg     byte " ***", 0x0d, 0x0a, "$"
no_z80_msg      byte "Z80 CPU required", 0x0d, 0x0a, "$"
unsupp_os_msg   byte "Operating system not supported", 0x0d, 0x0a, "$"
bdos_msg        byte "[BDOS $"
; CP/M 2 and 3 BDOS function names list for debugging. CP/M 3-only functions are
; prefixed with "3". Where functions differ between versions, the CP/M 2
; function is listed first followed by the CP/M 3 one. Functions not valid for
; either system are indicated with "". Function 152 (F_PARSE) is not included
; as it would extend the table a lot and is not something I plan to use.
                ifdef DEBUG
bdos_func_list      byte "P_TERMCPM\C_READ\C_WRITE\A_READ\"             ; 0-3
                    byte "A_WRITE\L_WRITE\C_RAWIO\GETIOB/3A_STATIN\"    ; 4-7
                    byte "SETIOB/3A_STATOUT\C_WRITESTR\C_READSTR\C_STAT\" ; 8-11
                    byte "S_BDOSVER\DRV_ALLRESET\DRV_SET\F_OPEN\"       ; 12-15
                    byte "F_CLOSE\F_SFIRST\F_SNEXT\F_DELETE\"           ; 16-19
                    byte "F_READ\F_WRITE\F_MAKE\F_RENAME\"              ; 20-23
                    byte "DRV_LOGINVEC\DRV_GET\F_DMAOFF\DRV_ALLOCVEC\"  ; 24-27
                    byte "DRV_SETRO\DRV_ROVEC\F_ATTRIB\DRV_DPB\"        ; 28-31
                    byte "F_USERNUM\F_READRAND\F_WRITERAND\F_SIZE\"     ; 32-35
                    byte "F_RANDREC\DRV_RESET\\\"                       ; 36-39
                    byte "F_WRITEZF\\\\"                                ; 40-43
                    byte "\\\\"                                         ; 44-47
                    byte "\3ACCSCB\3S_BIOS\\"                           ; 48-51
                    byte "\\\\"                                         ; 52-55
                    byte "\\\3P_LOAD\"                                  ; 56-59
                    byte "3CALLRSX\\\\"                                 ; 60-63
                    byte "\\\\"                                         ; 64-67
                    byte "\\\\"                                         ; 68-71
                    byte "\\\\"                                         ; 72-75
                    byte "\\\\"                                         ; 76-79
                    byte "\\\\"                                         ; 80-83
                    byte "\\\\"                                         ; 84-87
                    byte "\\\\"                                         ; 88-91
                    byte "\\\\"                                         ; 92-95
                    byte "\\3CLEANDISK\3F_TRUNCATE\"                    ; 96-99
                    byte "\\\\"                                         ; 100-103
                    byte "3T_SET\3T_GET\\\"                             ; 104-107
                    byte "3P_CODE\3C_MODE\3C_DELIMIT\3C_WRITEBLK\"      ; 108-111
                    byte "3L_WRITEBLK\"                                 ; 112
                    byte 0
                endif
;
;
; Pointers to BDOS console routines to be copied to con_vecs when BDOS is
; selected.
con_bdos_funcs  word conwch_bdos
                word conwms_bdos
                word conrch_bdos
                word const_bdos
;
; As above, but for the BIOS routines.
con_bios_funcs  word conwch_bios
                word conwms_bios
                word conrch_bios
                word const_bios
;
;
;
; *************
; * Variables *
; *************
;
; Note: linker "-c" option is used, so no data is initialised here.
                dseg                ; Data segment
;
gldn_x1         defs 4              ; Read long decimal temporary store
; cwpdlo (32-bit decimal print) variables
pdl_reg         defs 4              ; Working store
pdl_lz_flag     defs 1              ; Leading zero flag
pdl_ascii       defs 1              ; ASCII digit
cpmver          defs 1              ; CP/M version (packed BCD)
cbios_params    defs SBM_SIZE       ; BDOS_S_BIOS parameter block
;
; Console routine vectors. The order must match that in con_bdos_funcs and
; con_bios_funcs.
conwch_vec      defs 2              ; Vector to console write routine
conwms_vec      defs 2              ; Vector to console message write routine
conrch_vec      defs 2              ; Vector to console read routine
const_vec       defs 2              ; Vector to console status routine
;
                end

