; *******************************************************
; * I/O Routines for STran                              *
; * Version: V1.0                                       *
; * Merlin Skinner, 22/3/2021                           *
; *******************************************************
;
                title STran I/O
;
;
;
; ************
; * Includes *
; ************
;
;
                include "macros.i"
                include "cpm.i"
                include "stran.i"       ; Project include file
                include "cpm_utility.i" ; CP/M utilities
                include "cpm_maths.i"   ; Integer mathematics
;
;
;
; *************
; * Externals *
; *************
;
;
; Variables
                extern flags    ; Flags. See FLG_xxx in stran.i
;
; Functions
                public flush    ; Flush data port receive buffer
                public rxpkt    ; Receive a packet
                public txpkt    ; Transmit a packet
                public txdch    ; Transmit a character to the data port
                public rxdch    ; Read a character from the data port
;
;
                cseg                    ; Code segment
;
;
;
; ************
; * Transmit *
; ************
;
;
; Transmit a packet. The packet is assumed to be fully built, with all fields
; populated except the CRC. The FLG_TXB_VALID flag is set to indicate that the
; transmit buffer contains valid data.
; Call with:
; IY - pointer to packet buffer
txpkt           push bc
                push de
                push hl
;
                push iy
                pop hl
;
; Send start of packet character ("*" - not encoded)
                ld a, "*"
                call txdch
;
; Calculate total number of unencoded bytes to send.
                ex de, hl
                ld hl, PKT_DATA         ; Number of header bytes to send
                ld b, (iy + PKT_LENGTH + 1) ; Fetch data length in bytes
                ld c, (iy + PKT_LENGTH)
                add hl, bc
                push hl                 ; Copy length to BC
                pop bc
                ex de, hl
                ld de, 0                ; Set initial CRC
; BC - total bytes of header + data.
; DE - CRC
; HL - pointer to next byte to send (PSN).
txp_send_loop   push bc                 ; Save byte counter
                push de                 ; Save CRC
;
; Send data
                ld c, (hl)
                inc hl
                ld d, (hl)
                inc hl
                ld e, (hl)
                call tx_data_enc        ; Send 3 to 4 bytes encoded data
                pop de                  ; Restore CRC
;
; Update CRC.
                dec hl
                dec hl
                ex de, hl

; DE - pointer to next byte to send (PSN).
; HL - CRC
                ld a, (de)              ; Fetch byte 0
                call crc16x             ; Add to CRC
                inc de
;
                ld a, (de)              ; Fetch byte 1
                call crc16x             ; Add to CRC
                inc de
;
                ld a, (de)              ; Fetch byte 2
                call crc16x             ; Add to CRC
                inc de
;
                ex de, hl
                pop bc
; BC - total bytes of header + data.
; DE - CRC
; HL - pointer to next byte to send (PSN).
                dec bc                  ; Update byte counter
                dec bc
                dec bc
; If BC is zero or negative there is no more data to send.
                dec bc
; Now we can look for negative in all cases.
                ld a, b
                inc bc                  ; Restore decrement by 3 result
                and a
                jp p, txp_send_loop     
; Data sent, complete with padding (if required) to align to a 3-byte boundary.
;
; Send CRC
                ld c, e
                ld e, 0                 ; Pad byte
                call tx_data_enc        ; Send 3 to 4 bytes encoded data
;
; Flag tx_packet_buf contains valid data.
                ld hl, flags
                set FLG_TXB_VALID_BIT, (hl)
;
                pop hl
                pop de
                pop bc
                ret
;
;
; Transmit 3 bytes using the 3 to 4 bytes encoding scheme.
; Call with:
; CDE - data to transmit (C first)
tx_data_enc     push bc
                ld a, c
                srl a
                srl a
                add 0x3f
; A - <0, 1> <byte 0 bits 7 to 2>
                call txdch
                ld a, c
                rlca
                rlca
                rlca
                rlca
                and 0x30                ; Isolate byte 0 bits 1 to 0
                ld b, a
                ld a, d
                rrca
                rrca
                rrca
                rrca
                and 0x0f                ; Isolate byte 1 bits 7 to 4
                or b
                add 0x3f
; A - <0, 1> <byte 0 bits 1 to 0> <byte 1 bits 7 to 4>
                call txdch
                ld a, d
                rlca
                rlca
                and 0x3c                ; Isolate byte 1 bits 3 to 0
                ld b, a
                ld a, e
                rlca
                rlca
                and 0x03                ; Isolate byte 2 bits 7 to 6
                or b
                add 0x3f
; A - <0, 1> <byte 1 bits 3 to 0> <byte 2 bits 7 to 6>
                call txdch
                ld a, e
                and 0x3f                ; Isolate byte 2 bits 5 to 0
                add 0x3f
; A - <0, 1> <byte 2 bits 5 to 0>
                call txdch
                pop bc
                ret
;
;
; Transmit a character to the data port. This routine will wait if the
; transmitter is busy as it is not possible to determine status in all cases.
; The routine will panic if auto-port is active as in that state the required
; output port is not known. However, this should not be a problem as nothing
; is sent until a packet is received, after which auto-port is disabled.
; Call with:
; A - character to send.
txdch           push bc
                push de
                push hl
;
                ld c, a
                ld hl, BIOS_PUNCH       ; Assume AUX: output
                ld a, (flags)
                bit FLG_AUTO_BIT, a
                call nz, panic          ; Panic if auto-port is active
                bit FLG_AUX_BIT, a
                jr nz, txdch_go
txdch_aux       ld hl, BIOS_CONOUT      ; CON: output
txdch_go        call cbios
;
                pop hl
                pop de
                pop bc
                ret
;
;
;
; ***********
; * Receive *
; ***********
;
;
; Receive a packet.
; Call with:
; IY - pointer to packet buffer
; Returns with:
; A - 0x00 if OK or RXERR_...
rxpkt           push bc
                push de
                push hl
                ld (ret_sp), sp         ; Save stack for error exits
;
; Await start of packet character.
rxp_wait_start  ld sp, (ret_sp)         ; Restore saved stack pointer
; Reset counters (used for auto-port). As these are reset each character until
; a "*" is received, there is no chance that they will overflow.
                ld hl, 0
                ld (con_in_count), hl
                ld (aux_in_count), hl
                call rxdch              ; Wait for a character
                ld hl, flags
                bit FLG_BREAK_BIT, (hl)
                jp nz, rxp_break
                cp "*"
                jr nz, rxp_wait_start
;
; Start character found.
                ifdef DEBUG
                    ld a, "["
                    call conwch             ; Write character to console
                endif
                ld bc, 0                ; Byte count
                ld de, 0                ; Initial CRC
                push iy
                pop hl
;
; BC - total bytes of header + data
; DE - CRC
; HL - receive buffer pointer
rxp_loop        call rxp_read           ; Read three bytes
                cp RXERR_BREAK
                jr z, rxp_break
                and a
                jr nz, rxp_wait_start   ; Restart on other errors
;
; Handle length.
                inc bc                  ; Three more bytes
                inc bc
                inc bc
; Read until the entire packet is in the buffer.
                ld a, b
                and a
                jr nz, rxp_have_len
                ld a, c
                cp PKT_LENGTH + 2
                jr c, rxp_loop          ; Keep reading if no data length yet
; The length bytes are in the buffer.
rxp_have_len    push hl
                push de
                ld hl, PKT_DATA         ; Number of header bytes
                ld e, (iy + PKT_LENGTH) ; Fetch data length
                ld d, (iy + PKT_LENGTH + 1)
                add hl, de
; HL - number of bytes to read.
                dec hl                  ; Subtract 1 to catch equal case
                and a
                sbc hl, bc
                pop de
                pop hl
                jr nc, rxp_loop
;
; Read the CRC
                push de
                call rx_data_enc        ; Receive three bytes
; A - 0x00 if OK or RXERR_...
; CDE - received data (C first) unless brkflg is set.
                cp RXERR_BREAK
                jr z, rxp_break
                and a
                jr nz, rxp_wait_start   ; Restart on other errors
; CD - received checksum
                ld l, c
                ld h, d
                pop de
                ifdef DEBUG
                    ld a, "C"
                    call conwch             ; Write character to console
                    push hl
                    call cwphwd             ; Print HL in hexadecimal
                    ld a, ":"
                    call conwch             ; Write character to console
                    ld h, d
                    ld l, e
                    call cwphwd             ; Print HL in hexadecimal
                    pop hl
                endif
                and a
                sbc hl, de
                jr nz, rxp_crc_err
                ifdef DEBUG
                    ld a, "]"
                    call conwch             ; Write character to console
                endif
;
                ld hl, flags
                bit FLG_AUTO_BIT, (hl)
                jr z, rdc_exit_ok       ; Jump if not in auto-port mode
; We are in auto-port mode and have successfully received a packet. Check
; character counts to see where the packet came from.
                ld hl, (con_in_count)   ; Characters received from CON:
                ld de, (aux_in_count)   ; Characters received from AUX:
                and a
                sbc hl, de
                ld hl, flags
                res FLG_AUX_BIT, (hl)   ; Assume CON initially
                jr nc, rxp_auto_done    ; If AUX > CON then use AUX
; The packet came from AUX:
                set FLG_AUX_BIT, (hl)
rxp_auto_done   res FLG_AUTO_BIT, (hl)  ; Disable auto mode from now on
;               
rdc_exit_ok     xor a                   ; Success code
;
; Return with error code in A.
rxp_exit        ld sp, (ret_sp)         ; Restore saved stack pointer
                pop hl
                pop de
                pop bc
                ret
;
; Break (^C) detected.
rxp_break       ld a, RXERR_BREAK       ; Break detected
                jr rxp_exit
; 
rxp_crc_err     ld a, RXERR_CRC         ; CRC error
                jr rxp_exit
;
;
; Read three bytes and store them in the buffer. Update the CRC.
; Call and returns with:
; DE - CRC
; HL - buffer pointer
; Returns with:
; A - 0x00 if OK or RXERR_...
rxp_read        push bc
;
                push de                 ; Save CRC
                call rx_data_enc        ; Receive three bytes
; A - 0x00 if OK or RXERR_...
; CDE - received data (C first) unless brkflg is set.
                ld (hl), c              ; Save the data
                inc hl
                ld (hl), d
                inc hl
                ld (hl), e
                pop de                  ; Restore CRC
                and a
                jr nz, rxpr_exit        ; Exit on error
;
; Update CRC.
                dec hl                  ; Point to first byte again
                dec hl
                ex de, hl
; DE - pointer to next byte in buffer
; HL - CRC
                ld a, (de)              ; Fetch byte 0
                call crc16x             ; Add to CRC
                inc de
;
                ld a, (de)              ; Fetch byte 1
                call crc16x             ; Add to CRC
                inc de
;
                ld a, (de)              ; Fetch byte 2
                call crc16x             ; Add to CRC
                inc de
;
                ex de, hl
; DE - CRC
; HL - pointer to next byte in buffer
                xor a                   ; Success code
;
; Exit with zero or error code (RXERR_...) in A.
rxpr_exit       pop bc
                ret
;
;
; Receive 3 bytes using the 3 to 4 bytes encoding scheme.
; Returns with:
; A - 0x00 if OK or RXERR_...
; CDE - received data (C first) if A = 0x00
rx_data_enc     push hl
                ld l, b                 ; Preserve B (only)
;
                call rde_char           ; Read character 0
; A - <byte 0 bits 7 to 2>
                add a
                add a
                ld c, a
                call rde_char           ; Read character 1
; A - <byte 0 bits 1 to 0> <byte 1 bits 7 to 4>
                ld b, a
                rrca
                rrca
                rrca
                rrca
                and 0x03                ; Isolate byte 0 bits 1 to 0
                or c
                ld c, a
; C - decoded byte 0.
; B - 6 data bits recovered from character 1
                ld a, b
                rlca
                rlca
                rlca
                rlca
                and 0xf0                ; Isolate byte 1 bits 7 to 4
                ld d, a
                call rde_char           ; Read character 2
; A - <byte 1 bits 3 to 0> <byte 2 bits 7 to 6>
                ld b, a
                rrca
                rrca
                and 0x0f                ; Isolate byte 1 bits 3 to 0
                or d
                ld d, a
; D - decoded byte 1.
; B - 6 data bits recovered from character 2
                ld a, b
                rrca
                rrca
                and 0xc0                ; Isolate byte byte 2 bits 7 to 6
                ld e, a
                call rde_char           ; Read character 3
; A - <byte 2 bits 5 to 0>
                and 0x3f                ; Isolate byte 2 bits 5 to 0
                or e
                ld e, a
; E - decoded byte 2.
; CDE - received data (C first)
                ifdef DEBUG
                    ld a, "{"
                    call conwch             ; Write character to console
                    ld a, c
                    call cwphby             ; Print A in hexadecimal
                    ld a, ","
                    call conwch             ; Write character to console
                    ld a, d
                    call cwphby             ; Print A in hexadecimal
                    ld a, ","
                    call conwch             ; Write character to console
                    ld a, e
                    call cwphby             ; Print A in hexadecimal
                    ld a, "}"
                    call conwch             ; Write character to console
                    call cwnwln             ; Write new line characters to console
                endif
                xor a                   ; Set success code
;
rde_exit        ld b, l
                pop hl
                ret
;
; Read a character. For use by rx_data_enc as it makes direct jumps for error
; handling. B register is not preserved.
; A - bits 5 to 0 contain the 6 data bits recovered from this encoded character.
rde_char        call rxdch
                ld b, a
                ld a, (flags)
                and FLG_BREAK_MASK
                jr nz, rdec_break
                ld a, b
                sub 0x3f
                jr c, rdec_enc          ; Error if < 0x3f
                cp 0x40
                jr nc, rdec_enc         ; Error if character was >= 0x7f
                ret
;
rdec_break      inc sp                  ; Discard rde_char return address
                inc sp
                ld a, RXERR_BREAK       ; Break detected
                jr rde_exit
;
rdec_enc        inc sp                  ; Discard rde_char return address
                inc sp
                ld a, RXERR_ENC         ; 3 to 4 encoding error
                jr rde_exit
;
;
; Fetch a received character from the data port. If no character is available,
; wait until one arrives. CP/M 2.2 does not provide a method for reading the
; READER device port status, but we can do this using ZARC extensions if we are
; running on a ZARC system. This code also checks for break (^C) characters on
; the console port, whether this is the same as the data port or not. If a break
; is detected, FLG_BREAK is set.
; Returns with:
; A - received character.
rxdch           push bc
                push de
                push hl
;
                ld hl, flags
                bit FLG_AUTO_BIT, (hl)
                jr nz, rdc_auto
; Fixed port mode.
                bit FLG_AUX_BIT, (hl)
                jr z, rdc_read_con      ; Jump if using CON:
;
; Use AUX: port. We have to be a bit more careful here as we are looking for
; data on AUX: while doing our best to check for breaks on CON:
rdc_aux         bit FLG_AUXST_BIT, (hl)
                jr z, rdc_read_aux      ; Jump if no AUXIST or AUXOST
; We are using AUX: and status is available. Wait until a character is ready,
; polling for break as we do so. Note, the auxiliary input is called READER in
; CP/M 2.x.
rdc_wait        ld hl, BIOS_AUXIST      ; Status of auxiliary input
                call cbios
                and a
                jr nz, rdc_read_aux     ; Jump if a character awaits
                call rdc_con_break
                jr c, rdc_break         ; Jump if break detected
                jr rdc_wait
;
; Automatic port mode. Accept data from either port. This is only enabled for
; systems that support AUX: status.
rdc_auto        ld hl, BIOS_CONST       ; Status of CON: input
                call cbios
                and a
                jr nz, rdc_read_con
                ld hl, BIOS_AUXIST      ; Status of AUX: input
                call cbios
                and a
                jr nz, rdc_read_aux
                jr rdc_auto             ; Keep polling
;
; Read a character from CON:, waiting if required.
rdc_read_con    ld hl, BIOS_CONIN
                call cbios
; Perform break (^C) checks. How we do this depends on the mode.
                cp BREAK_CHAR
                jr z, rdc_break
                ld hl, (con_in_count)   ; Maintain count for auto port
                inc hl
                ld (con_in_count), hl
                jr rdc_exit
;
; Read a character from AUX:, waiting if required.
rdc_read_aux    call rdc_con_break      ; Check for break from console
                jr c, rdc_break
                ld hl, BIOS_READER
                call cbios
                ld hl, (aux_in_count)   ; Maintain count for auto port
                inc hl
                ld (aux_in_count), hl
                jr rdc_exit
;
; Break character detected.
rdc_break       ld hl, flags
                set FLG_BREAK_BIT, (hl)
;
; Return with character in A.
rdc_exit        pop hl
                pop de
                pop bc
                ret
;
; Check console port for break character.
; Returns with:
; Carry flag - set if break detected.
rdc_con_break   ld hl, BIOS_CONST       ; Console status
                call cbios
                and a
                jr z, rdcb_no_break     ; Exit if no character awaits
                ld hl, BIOS_CONIN       ; Console input
                call cbios
                cp BREAK_CHAR
                jr z, rdcb_break
rdcb_no_break   and a                   ; Flag no break detected
                ret
;
rdcb_break      scf                     ; Flag break detected
                ret
;
;
; Flush data port receive buffer. This works when the console port is the
; data port and / or when running on a CP/M 3.x or ZARC system. This code keeps
; reading and discarding data until no data is received for a reasonable period,
; defined by FLUSH_TIMER. This behaviour allows for delays caused by additional
; upstream buffers, such as those in a RS-232 to USB adaptor.
flush
; If not FLG_AUTO and FLG_AUX and not FLG_AUXST then we are attempting to flush
; without being able to check the status, which won't work. We don't need to
; worry about auto-port mode as this is trapped elsewhere.
                ld a, (flags)
                and FLG_AUTO_MASK | FLG_AUX_MASK | FLG_AUXST_MASK
                cp FLG_AUX_MASK
                ret z
;
                push bc
                push de
                push hl
;
                ld hl, flushing_msg     ; "Flushing serial port receive buffer"
                call conwms             ; Print $-terminated string to the console
;
; The timer is crude in that it really only sets the number of checks made
; before declaring the buffer empty. The actual time will depend on processor
; speed.
flu_reset       ld bc, FLUSH_TIMER
; Check the port status. This will determine whether we use CONST or AUXIST
; to check whether or not there is a character to read.
flu_loop        ld a, (flags)
                bit FLG_AUTO_BIT, a
                jr nz, flu_auto
; Not auto mode, so work out which port to do.
                bit FLG_AUX_BIT, a
                push af                 ; Save zero flag
                call z, flu_con         ; Flush CON: if selected
                pop af
                call nz, flu_aux        ; Flush AUX: if selected
                jr flu_pass_done
;
; Auto-port mode, so flush both.
flu_auto        call flu_con            ; Flush CON:
                call flu_aux            ; Flush AUX:
flu_pass_done     
;
; Keep going unless timer has expired.
                dec bc                  ; Adjust timer
                ld a, b
                or c
                jr nz, flu_loop
;
; Best effort flushing complete.
flu_done        pop hl
                pop de
                pop bc
                ret
;
; Read one character from CON: if there is one and modify timer in BC
; appropriately. Used by flush only.
flu_con         push bc
                ld hl, BIOS_CONST       ; Console status
; Check the port status using the appropriate function.
                call cbios
                pop bc
                and a
                ret z                   ; Exit if no character awaits
; There is a character awaiting, so read it and return.
                ld hl, BIOS_CONIN       ; Reader input
                call cbios
                ld bc, FLUSH_TIMER      ; Reset timer
                ret
;
; Read one character from AUX: if there is one and modify timer in BC
; appropriately. Used by flush only.
flu_aux         push bc
                ld hl, BIOS_AUXIST      ; Status of auxiliary input
; Check the port status using the appropriate function.
                call cbios
                pop bc
                and a
                ret z                   ; Exit if no character awaits
; There is a character awaiting, so read it and return.
                ld hl, BIOS_READER      ; Reader input
                call cbios
                ld bc, FLUSH_TIMER      ; Reset timer
                ret
;
;
;
; *************
; * Constants *
; *************
;
;
flushing_msg    byte "Flushing serial port receive buffer", 0x0d, 0x0a, "$"
;
;
;
; *************
; * Variables *
; *************
;
;
; Note: linker "-c" option is used, so no data is initialised here.
                dseg                ; Data segment
;
ret_sp          defs 2              ; Saved stack for error exits
con_in_count    defs 2              ; Characters received from CON:
aux_in_count    defs 2              ; Characters received from AUX:
;
                end

